<a href="https://colab.research.google.com/github/jiseokshin/FIT3181_A2/blob/main/FIT3181_DeepLearning_Assignment2_Official%5BMain%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color="#0b486b">  FIT3181: Deep Learning (2025) - Assignment 2 (Section I)</font>
***
*CE/Lecturer (Clayton):*  **Dr Trung Le** | trunglm@monash.edu <br/>
*Lecturer (Clayton):* **A/Prof Zongyuan Ge** | zongyuan.ge@monash.edu <br/>
*Lecturer (Malaysia):*  **Dr Arghya Pal** | arghya.pal@monash.edu <br/>
 <br/>
*Head Tutor 3181:*  **Ms Ruda Nie H** |  \[RudaNie.H@monash.edu \] <br/>
*Head Tutor 5215:*  **Ms Leila Mahmoodi** |  \[leila.mahmoodi@monash.edu \]

<br/> <br/>
Faculty of Information Technology, Monash University, Australia
***

# <font color="#0b486b">  Student Information</font>
***
Surname: **Shin**  <br/>
Firstname: **Jiseok**    <br/>
Student ID: **[33095310]**    <br/>
Email: **[jshi0072@student.monash.edu]**    <br/>
Your tutorial time: **[Thursday 2pm-5pm]**    <br/>
***

# <font color="0b486b">Assignment 2 – Deep Learning for Sequential Data</font>
### Due: <font color="red">11:55pm Sunday, 26 October 2025</font> (FIT3181)

#### <font color="red">Important note:</font> This is an **individual** assignment. It contributes **20%** to your final mark. Read the assignment instructions carefully.

## <font color="#0b486b">Assignment 2's Organization</font>
This assignment 2 has two (2) sections:
- Section 1: Fundamentals of RNNs (10 marks).
- Section 2: Deep Learning for Sequential Data (90 marks). This section is further divided into 4 parts.

The assignment 2 is organized in three (3) notebooks.
- Notebook 1 (this notebook) [Total: 30 marks] includes Section 1 as well as Part 1 and Part 2 of Section 2.
- Notebook 2 ([link](https://colab.research.google.com/drive/1m0mh9Mk4-AKEhgAHRwQdl5mc0x7SF7Tv?usp=sharing)) [Total: 40 marks] includes Part 3 of Section 2.
- Notebook 3 ([link](https://colab.research.google.com/drive/1JfMZeCkkvjZ5LvKNV-UnR10pl-RogMgF?usp=sharing)) [Total: 30 marks] includes Part 4 of Section 2.


## <font color="#0b486b">What to submit</font>

This assignment is to be completed individually and submitted to Moodle unit site. **By the due date, you are required to submit one  <font color="red; font-weight:bold">single zip file, named 33095310_assignment02_solution.zip</font> where `xxx` is your student ID, to the corresponding Assignment (Dropbox) in Moodle**. You can use Google Colab to do Assignment 2 but you need to save it to an `*.ipynb` file to submit to the unit Moodle.

**More importantly, if you use Google Colab to do this assignment, you need to first make a copy of this notebook on your Google drive**.

***For example, if your student ID is <font color="red; font-weight:bold">12356</font>, then gather all of your assignment solutions to a folder, create a zip file named <font color="red; font-weight:bold">123456_assignment02_solution.zip</font> and submit this file.***

Within this zip folder, you **must** submit the following files <u>for each part</u>:
1.	**`FIT3181_DeepLearning_Assignment2_Official[Main].ipynb`**:  this is your Python notebook solution source file.
1.	**`FIT3181_DeepLearning_Assignment2_Official[Main].html`**: this is the output of your Python notebook solution *exported* in HTML format.
1. **`FIT3181_DeepLearning_Assignment2_Official[RNNs].ipynb`**
1. **`FIT3181_DeepLearning_Assignment2_Official[RNNs].html`**
1. **`FIT3181_DeepLearning_Assignment2_Official[Transformers].ipynb`**
1. **`FIT3181_DeepLearning_Assignment2_Official[Transformers].html`**
1.	Any **extra files or folder** needed to complete your assignment (e.g., images used in your answers).



## Section 1: Fundamentals in RNNs

You need to **manually** implement a multi-timestep Recurrent Neural Network that can take an input as a 3D tensor `[batch_size, seq_len, input_size]` for a classification task.

<div style="text-align: right"><font color="red">[Total: 10 marks]</font></div>

In [1]:
import torch


In [2]:

torch.set_printoptions(sci_mode=False, precision=4)
torch.manual_seed(0)

We declare the relevant variables.

In [3]:
input_size = 5
seq_len = 4
batch_size = 8
hidden_size = 3
num_classes = 3

We create random inputs (i.e., `inputs`) and random labels (i.e., `random_labels`).

In [4]:
inputs = torch.randn(batch_size, seq_len, input_size)
random_labels = torch.randint(0, num_classes, (batch_size,))
print(inputs.shape)
print(random_labels)

torch.Size([8, 4, 5])
tensor([1, 2, 2, 2, 2, 0, 0, 0])


(1) In what follows, we need to declare the model parameters, which include the matrices $U$ (``[input_size, hidden_size]``), W (``[hidden_size, hidden_size]``), $V$ (``[hidden_size, num_classes]``) and the biases $b$ and $c$ for the hidden states and logits respectively.

<div style="text-align: right"><font color="red">[2 marks]</font></div>

In [5]:
#Insert your code here
U = torch.nn.Parameter(torch.randn(input_size, hidden_size) * (2/hidden_size)**0.5)
W = torch.nn.Parameter(torch.randn(hidden_size, hidden_size) * (2/hidden_size)**0.5)
b = torch.nn.Parameter(torch.zeros(hidden_size))
V = torch.nn.Parameter(torch.randn(hidden_size, num_classes) * (2/hidden_size)**0.5)
c = torch.nn.Parameter(torch.zeros(num_classes))


params = [U, W, b, V, c]
for p in params:
    p.requires_grad_(True)
    
print("U:", U.shape, "W:", W.shape, "b:", b.shape, "V:", V.shape, "c:", c.shape)



U: torch.Size([5, 3]) W: torch.Size([3, 3]) b: torch.Size([3]) V: torch.Size([3, 3]) c: torch.Size([3])


(2) Next you need to write the code to compute `hiddens` which is a 3D tensor of the shape ``[batch_size, seq_len, hidden_size]`` using the formula of the simple/standard RNN cells. You can freely modify the code below.

<div style="text-align: right"><font color="red">[2 marks]</font></div>

In [6]:
#Initialize hiddens for update.
hiddens = torch.zeros(batch_size, seq_len, hidden_size)

#Insert your code here
h_prev = torch.zeros(batch_size, hidden_size)
for t in range(seq_len):
    x_t = inputs[:, t, :]                               # (batch_size, input_size)
    h_t = torch.tanh(x_t @ U + h_prev @ W + b)          # (batch_size, hidden_size)
    hiddens[:, t, :] = h_t
    h_prev = h_t

print(hiddens.shape)
print(hiddens[:2, -1])

torch.Size([8, 4, 3])
tensor([[ 0.9996, -0.9977, -0.9888],
        [-0.9293,  0.9716, -0.8190]], grad_fn=<SelectBackward0>)


(3) In what follows, you need to write the code to compute the logits based on the last hidden state (``[batch_size, hidden_size]``) of hiddens.

<div style="text-align: right"><font color="red">[1 mark]</font></div>

In [7]:
h_last = hiddens[:, -1, :]
logits = h_last @ V + c       
print("logits.shape:", logits.shape)
print(logits)

logits.shape: torch.Size([8, 3])
tensor([[ 1.3990,  0.2307,  0.7709],
        [-1.1064,  0.1209,  0.8236],
        [-0.6812, -0.2259,  0.7966],
        [-1.2046, -0.2168, -0.7344],
        [-1.2082, -0.4272, -0.8664],
        [-1.1872, -0.2159, -0.7938],
        [-0.2276,  0.2471, -0.3473],
        [-1.2993, -0.3404, -0.8288]], grad_fn=<AddBackward0>)


(4) Write the code to compute the cross-entropy loss by comparing the logits to the labels. You can use PyTorch's built-in loss function.

<div style="text-align: right"><font color="red">[1 mark]</font></div>

In [8]:
import torch.nn.functional as F

In [9]:
#Insert your code here
criterion = torch.nn.CrossEntropyLoss()
loss = criterion(logits, random_labels)
print("loss:", loss.item())
print(loss)

loss: 1.206323504447937
tensor(1.2063, grad_fn=<NllLossBackward0>)


(5) Next, you need to do back-propagation to compute the gradients of the loss w.r.t. the model parameters. You can use PyTorch's built-in method to compute the gradients.

<div style="text-align: right"><font color="red">[2 marks]</font></div>

In [10]:
#Insert your code here

# Zero grads (in case this cell is re-run)
for p in params:
    if p.grad is not None:
        p.grad.zero_()

# Recompute forward (so graph is intact) and backward
h_prev = torch.zeros(batch_size, hidden_size)
hiddens = torch.zeros(batch_size, seq_len, hidden_size)
for t in range(seq_len):
    x_t = inputs[:, t, :]
    h_prev = torch.tanh(x_t @ U + h_prev @ W + b)
    hiddens[:, t, :] = h_prev

h_last = hiddens[:, -1, :]
logits = h_last @ V + c
loss = criterion(logits, random_labels)
loss.backward()

for name, p in zip(["U","W","b","V","c"], params):
    print(f"{name}.grad norm: {p.grad.norm().item():.6f}")

U.grad norm: 0.344451
W.grad norm: 0.275753
b.grad norm: 0.142836
V.grad norm: 0.791970
c.grad norm: 0.330426


(6) Finally, let assume that the learning rate $\eta = 0.1$, you need to write the code to **manually** update the new model parameters using the SGD manner.

<div style="text-align: right"><font color="red">[2 marks]</font></div>

In [11]:
#Insert your code here
lr = 0.1

#before
print(params[0][0, 0].item())

with torch.no_grad():
    for p in params:
        p -= lr * p.grad

# Check the same parameter after update
print(params[0][0, 0].item())


-0.7968389987945557
-0.8018071055412292


## Section 2: Deep Learning for Sequential Data

### <font color="#0b486b">Set random seeds</font>

We start with importing PyTorch and NumPy and setting random seeds for PyTorch and NumPy. You can use any seeds you prefer.

In [12]:
import os
import torch
import random
import requests
import pandas as pd
import numpy as np
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.nn.utils.rnn import pad_sequence
from transformers import BertTokenizer
import os
from six.moves.urllib.request import urlretrieve
from sklearn import preprocessing
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [13]:
def seed_all(seed=1029):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)  # if you are using multi-GPU.
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True
seed_all(seed=1234)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

## <font color="#0b486b">Download and preprocess the data</font>

<div style="text-align: right"><font color="red; font-weight:bold"><span></div>

The dataset we use for this assignment is a question classification dataset for which the training set consists of $5,500$ questions belonging to 6 coarse question categories including:
- abbreviation (ABBR),
- entity (ENTY),
- description (DESC),
- human (HUM),
- location (LOC) and
- numeric (NUM).

In this assignment, we will utilize a subset of this dataset, containing $2,000$ questions for training and validation. We will use 80% of those 2000 questions for trainning and the rest for validation.


Preprocessing data is a crucial initial step in any machine learning or deep learning project. The *TextDataManager* class simplifies the process by providing functionalities to download and preprocess data specifically designed for the subsequent questions in this assignment. It is highly recommended to gain a comprehensive understanding of the class's functionality by **carefully reading** the content provided in the *TextDataManager* class before proceeding to answer the questions.

In [14]:
class DataManager:
    """
    This class manages and preprocesses a simple text dataset for a sentence classification task.

    Attributes:
        verbose (bool): Controls verbosity for printing information during data processing.
        max_sentence_len (int): The maximum length of a sentence in the dataset.
        str_questions (list): A list to store the string representations of the questions in the dataset.
        str_labels (list): A list to store the string representations of the labels in the dataset.
        numeral_labels (list): A list to store the numerical representations of the labels in the dataset.
        numeral_data (list): A list to store the numerical representations of the questions in the dataset.
        random_state (int): Seed value for random number generation to ensure reproducibility.
            Set this value to a specific integer to reproduce the same random sequence every time. Defaults to 6789.
        random (np.random.RandomState): Random number generator object initialized with the given random_state.
            It is used for various random operations in the class.

    Methods:
        maybe_download(dir_name, file_name, url, verbose=True):
            Downloads a file from a given URL if it does not exist in the specified directory.
            The directory and file are created if they do not exist.

        read_data(dir_name, file_names):
            Reads data from files in a directory, preprocesses it, and computes the maximum sentence length.
            Each file is expected to contain rows in the format "<label>:<question>".
            The labels and questions are stored as string representations.

        manipulate_data():
            Performs data manipulation by tokenizing, numericalizing, and padding the text data.
            The questions are tokenized and converted into numerical sequences using a tokenizer.
            The sequences are padded or truncated to the maximum sequence length.

        train_valid_test_split(train_ratio=0.9):
            Splits the data into training, validation, and test sets based on a given ratio.
            The data is randomly shuffled, and the specified ratio is used to determine the size of the training set.
            The string questions, numerical data, and numerical labels are split accordingly.
            TensorFlow `Dataset` objects are created for the training and validation sets.


    """

    def __init__(self, verbose=True, random_state=6789):
        self.verbose = verbose
        self.max_sentence_len = 0
        self.str_questions = list()
        self.str_labels = list()
        self.numeral_labels = list()
        self.maxlen = None
        self.numeral_data = list()
        self.random_state = random_state
        self.random = np.random.RandomState(random_state)

    @staticmethod
    def maybe_download(dir_name, file_name, url, verbose=True):
        if not os.path.exists(dir_name):
            os.mkdir(dir_name)
        if not os.path.exists(os.path.join(dir_name, file_name)):
            urlretrieve(url + file_name, os.path.join(dir_name, file_name))
        if verbose:
            print("Downloaded successfully {}".format(file_name))

    def read_data(self, dir_name, file_names):
        self.str_questions = list()
        self.str_labels = list()
        for file_name in file_names:
            file_path= os.path.join(dir_name, file_name)
            with open(file_path, "r", encoding="latin-1") as f:
                for row in f:
                    row_str = row.split(":")
                    label, question = row_str[0], row_str[1]
                    question = question.lower()
                    self.str_labels.append(label)
                    self.str_questions.append(question[0:-1])
                    if self.max_sentence_len < len(self.str_questions[-1]):
                        self.max_sentence_len = len(self.str_questions[-1])

        # turns labels into numbers
        le = preprocessing.LabelEncoder()
        le.fit(self.str_labels)
        self.numeral_labels = np.array(le.transform(self.str_labels))
        self.str_classes = le.classes_
        self.num_classes = len(self.str_classes)
        if self.verbose:
            print("\nSample questions and corresponding labels... \n")
            print(self.str_questions[0:5])
            print(self.str_labels[0:5])

    def manipulate_data(self):
        self.tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
        vocab = self.tokenizer.get_vocab()
        self.word2idx = {w: i for i, w in enumerate(vocab)}
        self.idx2word = {i:w for w,i in self.word2idx.items()}
        self.vocab_size = len(self.word2idx)

        token_ids = []
        num_seqs = []
        for text in self.str_questions:  # iterate over the list of text
          text_seqs = self.tokenizer.tokenize(str(text))  # tokenize each text individually
          # Convert tokens to IDs
          token_ids = self.tokenizer.convert_tokens_to_ids(text_seqs)
          # Convert token IDs to a tensor of indices using your word2idx mapping
          seq_tensor = torch.LongTensor(token_ids)
          num_seqs.append(seq_tensor)  # append the tensor for each sequence

        # Pad the sequences and create a tensor
        if num_seqs:
          self.numeral_data = pad_sequence(num_seqs, batch_first=True)  # Pads to max length of the sequences
          self.num_sentences, self.maxlen = self.numeral_data.shape

    def train_valid_test_split(self, train_ratio=0.8, test_ratio = 0.1):
        train_size = int(self.num_sentences*train_ratio) +1
        test_size = int(self.num_sentences*test_ratio) +1
        valid_size = self.num_sentences - (train_size + test_size)
        data_indices = list(range(self.num_sentences))
        random.shuffle(data_indices)
        self.train_str_questions = [self.str_questions[i] for i in data_indices[:train_size]]
        self.train_numeral_labels = self.numeral_labels[data_indices[:train_size]]
        train_set_data = self.numeral_data[data_indices[:train_size]]
        train_set_labels = self.numeral_labels[data_indices[:train_size]]
        train_set_labels = torch.from_numpy(train_set_labels)
        train_set = torch.utils.data.TensorDataset(train_set_data, train_set_labels)
        self.test_str_questions = [self.str_questions[i] for i in data_indices[-test_size:]]
        self.test_numeral_labels = self.numeral_labels[data_indices[-test_size:]]
        test_set_data = self.numeral_data[data_indices[-test_size:]]
        test_set_labels = self.numeral_labels[data_indices[-test_size:]]
        test_set_labels = torch.from_numpy(test_set_labels)
        test_set = torch.utils.data.TensorDataset(test_set_data, test_set_labels)
        self.valid_str_questions = [self.str_questions[i] for i in data_indices[train_size:-test_size]]
        self.valid_numeral_labels = self.numeral_labels[data_indices[train_size:-test_size]]
        valid_set_data = self.numeral_data[data_indices[train_size:-test_size]]
        valid_set_labels = self.numeral_labels[data_indices[train_size:-test_size]]
        valid_set_labels = torch.from_numpy(valid_set_labels)
        valid_set = torch.utils.data.TensorDataset(valid_set_data, valid_set_labels)
        self.train_loader = DataLoader(train_set, batch_size=64, shuffle=True)
        self.test_loader = DataLoader(test_set, batch_size=64, shuffle=False)
        self.valid_loader = DataLoader(valid_set, batch_size=64, shuffle=False)

In [15]:
print('Loading data...')
DataManager.maybe_download("data", "train_2000.label", "http://cogcomp.org/Data/QA/QC/")

dm = DataManager()
dm.read_data("data/", ["train_2000.label"])

Loading data...
Downloaded successfully train_2000.label

Sample questions and corresponding labels... 

['manner how did serfdom develop in and then leave russia ?', 'cremat what films featured the character popeye doyle ?', "manner how can i find a list of celebrities ' real names ?", 'animal what fowl grabs the spotlight after the chinese year of the monkey ?', 'exp what is the full form of .com ?']
['DESC', 'ENTY', 'DESC', 'ENTY', 'ABBR']


In [16]:
dm.manipulate_data()
dm.train_valid_test_split(train_ratio=0.8, test_ratio = 0.1)

In [17]:
for x, y in dm.train_loader:
    print(x.shape, y.shape)
    break

torch.Size([64, 36]) torch.Size([64])


## <font color="#0b486b">Part 1: Using Word2Vect to transform texts to vectors </font>

<div style="text-align: right"><font color="red; font-weight:bold">[Total marks for this part: 10 marks]<span></div>

In [18]:
import gensim.downloader as api
from gensim.models import Word2Vec
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
import numpy as np

#### <font color="red">**Question 1.1**</font>
**Write code to download the pretrained model *glove-wiki-gigaword-100*. Note that this model transforms a word in its dictionary to a $100$ dimensional vector.**

**Write code for the function *get_word_vector(word, model)* used to transform a word to a vector using the pretrained Word2Vect model *model*. Note that for a word not in the vocabulary of our *word2vect*, you need to return a vector $0$ with 100 dimensions.**

<div style="text-align: right"><font color="red">[2 marks]</font></div>

In [19]:
word2vect = api.load("glove-wiki-gigaword-100")

[==================================================] 100.0% 128.1/128.1MB downloaded


In [20]:
def get_word_vector(word, model):
    try:
        vector = model.get_vector(word)
    except:
        vector = np.zeros(model.vector_size, dtype=np.float32)
    return vector

#### <font color="red">**Question 1.2**</font>

**Write the code for the function `get_sentence_vector(sentence, important_score=None, model= None)`. Note that this function will transform a sentence to a 100-dimensional vector using the pretrained model *model*. In addition, the list *important_score* which has the same length as the *sentence* specifies the important scores of the words in the sentence. In your code, you first need to apply *softmax* function over *important_score* to obtain the important weight *important_weight* which forms a probability over the words of the sentence. Furthermore, the final vector of the sentence will be weighted sum of the individual vectors for words and the weights in *important_weight*.**
- $important\_weight = softmax(important\_score)$.
- $final\_vector= important\_weight[1]\times v[1] + important\_weight[2]\times v[2] + ...+ important\_weight[T]\times v[T]$ where $T$ is the length of the sentence and $v[i]$ is the vector representation of the $i-th$  word in this sentence.

**Note that if `important_score=None` is set by default, your function should return the average of all representation vectors corresponding to set `important_score=[1,1,...,1]`.**

<div style="text-align: right"><font color="red">[2 marks]</font></div>

In [23]:

def _softmax(x):
    x = np.asarray(x, dtype=np.float32)
    x -= x.max()                      # numerical stability
    ex = np.exp(x)
    return ex / (ex.sum() + 1e-12)

#If important_score is None, use a uniform average. If provided, softmax the scores and take a weighted sum.
def get_sentence_vector(sentence, important_score=None, model=None):
    """important_score: list/array (len = #tokens). If None -> uniform average.
    model: pretrained KeyedVectors (e.g., GloVe).
    """
    assert model is not None, "Please pass the pretrained model"

    # very simple tokenization (assignment usually expects this)
    tokens = sentence.strip().lower().split()
    if len(tokens) == 0:
        return np.zeros(model.vector_size, dtype=np.float32)

    # collect word vectors (OOV -> zeros)
    vecs = np.stack([get_word_vector(w, model) for w in tokens], axis=0)  # [T, D]

    if important_score is None:
        # uniform average
        feature_vector = vecs.mean(axis=0)
    else:
        # softmax -> weights sum to 1
        weights = _softmax(important_score)           # [T]
        feature_vector = (weights[:, None] * vecs).sum(axis=0)

    return feature_vector.astype(np.float32)

#### <font color="red">**Question 1.3**</font>

**Write code to transform questions in *dm.train_str_questions* and *dm.valid_str_questions* to feature vectors. Note that after running the following cells, you must have $X\_train$ and $X\_valid$ which are two NumPy arrays of the feature vectors and $y\_train$ and $y\_valid$ which are two arrays of numeric labels (Hint: *dm.train_numeral_labels* and *dm.valid_numeral_labels*). You can add more lines to the following cells if necessary. In addition, you should decide the *important_score* by yourself. For example, the 1st score is 1, the 2nd score is decayed by 0.9, the 3rd is decayed by 0.9, and so on.**

<div style="text-align: right"><font color="red">[2 marks]</font></div>

In [24]:

def decayed_importance(n_tokens, gamma=0.9):
    return np.power(gamma, np.arange(n_tokens, dtype=np.float32)) # [1, gamma, gamma^2, ...]  → any length T

In [25]:
print("Transform training set to feature vectors...")
X_train = []
y_train = dm.train_numeral_labels
for s in dm.train_str_questions:
    T = max(1, len(s.strip().split()))
    imp = decayed_importance(T, gamma=0.9)
    x = get_sentence_vector(s, important_score=imp, model=word2vect)
    X_train.append(x)
X_train = np.stack(X_train, axis=0).astype(np.float32)

Transform training set to feature vectors...


In [26]:
print("Transform validation set to feature vectors...")
X_valid = []
y_valid = dm.valid_numeral_labels
for s in dm.valid_str_questions:
    T = max(1, len(s.strip().split()))
    imp = decayed_importance(T, gamma=0.9)
    x = get_sentence_vector(s, important_score=imp, model=word2vect)
    X_valid.append(x)
X_valid = np.stack(X_valid, axis=0).astype(np.float32)

Transform validation set to feature vectors...


In [27]:
print("Shapes → X_train:", X_train.shape, " y_train:", y_train.shape,
      "| X_valid:", X_valid.shape, " y_valid:", y_valid.shape)

Shapes → X_train: (1601, 100)  y_train: (1601,) | X_valid: (198, 100)  y_valid: (198,)


#### <font color="red">**Question 1.4**</font>

**It is now to use *MinMaxScaler(feature_range=(-1,1))* in scikit-learn to scale both training and validation sets to the range $(-1,1)$.**

<div style="text-align: right"><font color="red">[2 marks]</font></div>

In [28]:
#Insert your code
scaler = MinMaxScaler(feature_range=(-1, 1))
X_train_scaled = scaler.fit_transform(X_train)   # fit on TRAIN only
X_valid_scaled = scaler.transform(X_valid)       # transform VALID with same scaler


#### <font color="red">**Question 1.5**</font>
**Train a Logistic Regression model on the training set and then evaluate on the validation set.** You can use any classification metrics in `sklearn` for evaluation.
<div style="text-align: right"><font color="red">[2 marks]</font></div>

In [31]:
from sklearn.linear_model import LogisticRegression
#Insert your code
# multinomial logistic regression (softmax) for 6 classes
logreg = LogisticRegression(
    multi_class="multinomial",
    solver="lbfgs",
    max_iter=1000,
    random_state=0)
logreg.fit(X_train_scaled, y_train)

/Users/jiseok/miniforge3/envs/nlp/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=1000, multi_class='multinomial', random_state=0)

In [32]:
from sklearn import metrics
#Insert your code
# evaluating validation set 
y_pred = logreg.predict(X_valid_scaled)

val_acc   = metrics.accuracy_score(y_valid, y_pred)
f1_macro  = metrics.f1_score(y_valid, y_pred, average="macro")
f1_weight = metrics.f1_score(y_valid, y_pred, average="weighted")

print(f"Validation accuracy: {val_acc:.4f}")
print(f"F1 (macro): {f1_macro:.4f} | F1 (weighted): {f1_weight:.4f}")

# per-class report
labels = np.arange(dm.num_classes)
print(metrics.classification_report(
    y_valid, y_pred,
    labels=labels,
    target_names=list(dm.str_classes),
    zero_division=0
))

# confusion matrix (rows = true, cols = predicted)
print("Confusion matrix:\n", metrics.confusion_matrix(y_valid, y_pred, labels=labels))

Validation accuracy: 0.9040
F1 (macro): 0.8598 | F1 (weighted): 0.9031
              precision    recall  f1-score   support

        ABBR       1.00      0.50      0.67         2
        DESC       0.91      0.86      0.89        36
        ENTY       0.89      0.87      0.88        54
         HUM       0.96      1.00      0.98        52
         LOC       0.84      0.90      0.87        29
         NUM       0.88      0.88      0.88        25

    accuracy                           0.90       198
   macro avg       0.91      0.83      0.86       198
weighted avg       0.90      0.90      0.90       198

Confusion matrix:
 [[ 1  1  0  0  0  0]
 [ 0 31  2  1  1  1]
 [ 0  2 47  1  2  2]
 [ 0  0  0 52  0  0]
 [ 0  0  3  0 26  0]
 [ 0  0  1  0  2 22]]


We now declare the `BaseTrainer` class, which will be used later to train the subsequent deep learning models for text data.

In [33]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

class BaseTrainer:
    def __init__(self, model, criterion, optimizer, train_loader, val_loader):
        self.model = model
        self.criterion = criterion  #the loss function
        self.optimizer = optimizer  #the optimizer
        self.train_loader = train_loader  #the train loader
        self.val_loader = val_loader  #the valid loader

    #the function to train the model in many epochs
    def fit(self, num_epochs):
        self.num_batches = len(self.train_loader)

        for epoch in range(num_epochs):
            print(f'Epoch {epoch + 1}/{num_epochs}')
            train_loss, train_accuracy = self.train_one_epoch()
            val_loss, val_accuracy = self.validate_one_epoch()
            print(
                f'{self.num_batches}/{self.num_batches} - train_loss: {train_loss:.4f} - train_accuracy: {train_accuracy*100:.4f}% \
                - val_loss: {val_loss:.4f} - val_accuracy: {val_accuracy*100:.4f}%')

    #train in one epoch, return the train_acc, train_loss
    def train_one_epoch(self):
        self.model.train()
        running_loss, correct, total = 0.0, 0, 0
        for i, data in enumerate(self.train_loader):
            inputs, labels = data
            inputs, labels = inputs.to(device), labels.to(device)
            self.optimizer.zero_grad()
            outputs = self.model(inputs)
            loss = self.criterion(outputs, labels)
            loss.backward()
            self.optimizer.step()

            running_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
        train_accuracy = correct / total
        train_loss = running_loss / self.num_batches
        return train_loss, train_accuracy

    #evaluate on a loader and return the loss and accuracy
    def evaluate(self, loader):
        self.model.eval()
        loss, correct, total = 0.0, 0, 0
        with torch.no_grad():
            for data in loader:
                inputs, labels = data
                inputs, labels = inputs.to(device), labels.to(device)
                outputs = self.model(inputs)
                loss = self.criterion(outputs, labels)
                loss += loss.item()
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        accuracy = correct / total
        loss = loss / len(self.val_loader)
        return loss, accuracy

    #return the val_acc, val_loss, be called at the end of each epoch
    def validate_one_epoch(self):
      val_loss, val_accuracy = self.evaluate(self.val_loader)
      return val_loss, val_accuracy

## <font color="#0b486b">Part 2: Text CNN for sequence modeling and neural embedding </font>

<div style="text-align: right"><font color="red; font-weight:bold">[Total marks for this part: 10 marks]<span></div>

**In what follows, you are required to complete the code for Text CNN for sentence classification. The paper of Text CNN can be found at this [link](https://www.aclweb.org/anthology/D14-1181.pdf). Here is the description of the Text CNN that you need to construct.**
- There are three attributes (properties or instance variables): *embed_size, state_size, data_manager*.
  - `embed_size`: the dimension of the vector space for which the words are embedded to using the embedding matrix.
  - `state_size`: the number of filters used in *Conv1D* (reference [here](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html)).
  - `data_manager`: the data manager to store information of the dataset.
- The detail of the computational process is as follows:
  - Given input $x$, we embed $x$ using the embedding matrix to obtain an $3D$ tensor $[batch\_size, seq\_len, embed\_size]$ as $e$.
  - We feed $e$ to three *Conv1D* layers, each of which has $state\_size$ filters, activation= $relu$, and $kernel\_size= 3, 5, 7$ respectively to obtain $h1, h2, h3$. Note that each $h1, h2, h3$ is a 3D tensor with the shape $[batch\_size, state\_size, output\_size]$. Moreover, you need to apply *Conv1D* to the $seq\_len$ dimension.
  - We then apply *GlobalMaxPool1D()* (reference [here](https://pytorch.org/docs/stable/generated/torch.nn.functional.max_pool1d.html#torch.nn.functional.max_pool1d)) over $h1, h2, h3$ to obtain 2D tensors stored in $h1, h2, h3$ again.
  - We then concatenate three 2D tensors $h1, h2, h3$ to obtain $h$ with the shape $\left[batch\_size, 3\times state\_size\right]$. Note that you need to specify the axis to concatenate.
  - We finally build up one dense layer $\left[3\times state\_size, num\_classes\right]$  on the top of $h$ for classification.
  

In [39]:
import torch.nn as nn
import torch.nn.functional as F

#You can modify the code if you want but need to keep the skeleton
class TextCNN(torch.nn.Module):
    def __init__(self, embed_size= 128, state_size=16, data_manager=None):
        super(TextCNN, self).__init__()
        self.data_manager = data_manager
        self.embed_size = embed_size
        self.state_size = state_size
        #declare the necessary layers here
        self.embed = nn.Embedding(self.data_manager.vocab_size, self.embed_size)
        self.conv1d_1 = nn.Conv1d(in_channels=self.embed_size, out_channels=self.state_size,
                                  kernel_size=3, padding=1, dilation=1)
        self.conv1d_2 = nn.Conv1d(in_channels=self.embed_size, out_channels=self.state_size,
                                  kernel_size=5, padding=2, dilation=1)
        self.conv1d_3 = nn.Conv1d(in_channels=self.embed_size, out_channels=self.state_size,
                                  kernel_size=7, padding=3, dilation=1)
        
        self.dropout = nn.Dropout(0.5)

        self.fc = nn.Linear(state_size*3, self.data_manager.num_classes)



    def forward(self, x):
        e = self.embed(x)   # [B, T, E]
        #permute x before applying Conv1D
        e= e.permute(0,2,1)

        #applying Conv1D
        # [B, S, L]
        h1 = F.relu(self.conv1d_1(e))   
        h2 = F.relu(self.conv1d_2(e))   
        h3 = F.relu(self.conv1d_3(e))   

        #apply GlobalMaxPool
        # [B, state_size]
        h1 = F.adaptive_max_pool1d(h1, 1).squeeze(-1)   
        h2 = F.adaptive_max_pool1d(h2, 1).squeeze(-1)   
        h3 = F.adaptive_max_pool1d(h3, 1).squeeze(-1)

        h =  torch.cat((h1, h2, h3), dim=1)     # [B, 3*state_size]
        h = self.fc(h)
        return h

We declare `text_cnn` and train on several epochs (e.g., `50 epochs`).


In [40]:
text_cnn = TextCNN(data_manager=dm).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(text_cnn.parameters(), lr=0.001)
trainer = BaseTrainer(model=text_cnn, criterion=criterion, optimizer=optimizer, train_loader=dm.train_loader, val_loader=dm.valid_loader)
trainer.fit(num_epochs=50)

Epoch 1/50
26/26 - train_loss: 1.5139 - train_accuracy: 47.9076%                 - val_loss: 0.4696 - val_accuracy: 76.2626%
Epoch 2/50
26/26 - train_loss: 0.7301 - train_accuracy: 84.6346%                 - val_loss: 0.1886 - val_accuracy: 85.3535%
Epoch 3/50
26/26 - train_loss: 0.3764 - train_accuracy: 91.4428%                 - val_loss: 0.0993 - val_accuracy: 93.9394%
Epoch 4/50
26/26 - train_loss: 0.2228 - train_accuracy: 95.6902%                 - val_loss: 0.0532 - val_accuracy: 94.4444%
Epoch 5/50
26/26 - train_loss: 0.1394 - train_accuracy: 97.8139%                 - val_loss: 0.0364 - val_accuracy: 94.4444%
Epoch 6/50
26/26 - train_loss: 0.0919 - train_accuracy: 99.3754%                 - val_loss: 0.0239 - val_accuracy: 95.4545%
Epoch 7/50
26/26 - train_loss: 0.0692 - train_accuracy: 99.6877%                 - val_loss: 0.0202 - val_accuracy: 94.9495%
Epoch 8/50
26/26 - train_loss: 0.0528 - train_accuracy: 99.5003%                 - val_loss: 0.0134 - val_accuracy: 95.4545%


We evaluate the trained model on the testing set.

In [41]:
test_loss, test_acc = trainer.evaluate(dm.test_loader)
print(f'test_loss: {test_loss:.4f} - test_accuracy: {test_acc*100:.4f}%')

test_loss: 0.1381 - test_accuracy: 97.0149%
